Handle qemu errors gracefully
Presently a qemu error like unknown CPU-model isn't handled gracefully and a test
that times-out in such a case will be reported as 'PASSED'. For example

$ ./ppc-boot.sh pseriesle6

pseriesle6 : spawn /usr/bin/qemu-system-ppc64 -m 1G -M pseries -cpu POWER6
-nodefaults -kernel ./buildroot/qemu_ppc64le_pseries-latest/vmlinux -append
root=/dev/sda -drive
file=./buildroot/qemu_ppc64le_pseries-latest/rootfs.ext2,if=scsi,format=raw -net
nic -net user -serial mon:stdio -nographic -snapshot

qemu-system-ppc64: unable to find CPU model 'POWER6'
<snip>
(PASSED)

To fix this update the expect script to watch out for qemu reported errors and
exit with code '6' in such a case. With the patch ppc-boot.sh correctly reports
'FAILED' for the above test case as shown below:

$ ./ppc-boot.sh pseriesle6
pseriesle6 : spawn /usr/bin/qemu-system-ppc64 -m 1G -M pseries -cpu POWER6
-nodefaults -kernel ./buildroot/qemu_ppc64le_pseries-latest/vmlinux -append
root=/dev/sda -drive
file=./buildroot/qemu_ppc64le_pseries-latest/rootfs.ext2,if=scsi,format=raw -net
nic -net user -serial mon:stdio -nographic -snapshot

qemu-system-ppc64: unable to find CPU model 'POWER6'
ERROR: unable to find CPU model 'POWER6'
(FAILED)

Signed-off-by: Vaibhav Jain <vaibhav@linux.ibm.com>